create table report (
    id bigint primary key generated by default as identity,
    name varchar(256),
    date timestamp not null constraint date_unique unique,
    diet text,
    photo oid,
    well_being text,
    behavior text
);