create table pet (
    id bigint primary key generated by default as identity,
    name varchar(256) constraint name_unique unique,
    adopted boolean,
    report_id bigint constraint rep_id references report
);