create table owner (
    id bigint primary key generated by default as identity,
    id_chat bigint,
    name varchar(256),
    date timestamp not null,
    pet_id bigint constraint pet_id references pet,
    unique (id_chat, pet_id)
);